name: DisasterPlugin
version: '${project.version}'
main: mtkb.disaster.disasterplugin.DisasterPlugin
api-version: '1.20'
commands:
  disaster:
    description: Commands associated with the disaster plugin.
    usage: /disaster (enable | disable | force | time | countdown) <time | disasterId | effectId | countdown> <countdown>
    aliases: [dis, d]